### ISSUE TITLE
Accept invitation as project collaborator

### ISSUE THREAD

**Issue by peterennisrda** [rdaray/GitSet#1]
@rdaray 

I now have push access.
The settings for this process need to be recorded in a doc.

Next step is to define the setup so that PRs must be made on a
separate branch and can only be merged with at least one review
from a team member.

![Capture145](https://user-images.githubusercontent.com/1280523/56619923-1b7e8e00-65dc-11e9-843e-1706908b942c.png)
![Capture146](https://user-images.githubusercontent.com/1280523/56619928-1f121500-65dc-11e9-979e-ea78a333b1e3.png)
![Capture147](https://user-images.githubusercontent.com/1280523/56619936-233e3280-65dc-11e9-98dd-c00432819561.png)

**Comment by rdaray** [comment]
Procedures documented in 
[Setup_and_Working_with_GitHub_20190429_v003_RAC.docx](https://github.com/rdaray/GitSet/files/3129413/Setup_and_Working_with_GitHub_20190429_v003_RAC.docx)
Will add to readme as well.
