### ISSUE TITLE
Document setup for PRs to be made on a separate branch

### ISSUE THREAD

**Issue by peterennisrda** [rdaray/GitSet#2]
@rdaray 

Define the setup so that PRs must be made on a
separate branch and can only be merged with at least one review
from a team member.

Create a ticket with GitHub if needed.

**Comment by rdaray** [comment]
@peterennisrda 
Have created a doc with these procedures:
[Setup_and_Working_with_GitHub_20190423_v002_RAC.docx](https://github.com/rdaray/GitSet/files/3129359/Setup_and_Working_with_GitHub_20190423_v002_RAC.docx)
Will copy a version of this into readme.
